### ISSUE TITLE
CTX-Floods Backend Deployment Checklist

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/ctxfloods#311]
**Required**
- [ ] Single .travis.yml file for all branches
- [ ] serverless.yml file that only requires 1 invocation
  - [ ] extract variables from created resources
- [ ] Have option to trigger feature branch deployment
- [ ] Seed new databases with ```addSetupData``` and ```addLegacyCrossings```
- [ ] Save branch-specific secret env variables in Travis console
- [ ] Document deployment, local dev setup, and env variables
- [ ] When branch=master, trigger 2 deployments -> one for legacy-sync, one not
  - [ ] have custom env vars for each deployment

**Nice to Have**
- [ ] Customize Name of S3 Bucket for Feature Branches
  - [ ] Assign Appropriate Security Credentials for deployed Feature Branches
- [ ] Clean up yarn scripts
- [ ] Clean up PG env variables
- [ ] Automatically sync to frontend
- [ ] Clean up error logs thrown during testing
- [ ] Clean up hardcoded ports 

**Investigate**
- [ ] Are lokka transports working even when hardcoded to localhost?
- [ ] Create IAM users for feature branch and prod deployments
- [ ] switch to postgraphile from postgraphql
- [ ] re-enabled/disable syncLegacyHandler in serverless.yml
