### ISSUE TITLE
Public Launch Checklist

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/ctxfloods#421]
**Security and Credentials**
- [ ] Follow up on security audit findings #200
- [ ] Database Security #200 
  - [x] Change master password
  - [x] Update api username/password
  - [x] Remove hardcoded auth in js code
  - [x] Remove hardcoded auth in sql code
  - [x] Create different passwords for prod vs dev deployments
  - [x] Revisit catch-all "security definer" permissions on functions 
  - [x] restrict access to sensitive fields (like users emails) #400
  - [ ] move db into more secure VPC
- [ ] Change and secure places.api.here credentials  #414
- [ ] Add Security to Lambda Functions #466 

**Scalability**
- [ ] Implement pgBouncer to manage postgres pool connections on prod
- [ ] Conduct load testing #289 #399 
- [ ] Check efficiency of sql queries/indexing
- [x] Add database monitoring

**City**
- [ ] Get official austintexas.gov email for ctxfloods #401 

**Deployment**
- [ ] Implement a database backup strategy beyond default AWS automation
- [x] Disaster Recovery - process for rolling back a failed deployment #474
- [x] Speed up Travis deployment time
  - emergency hotfixes must be implemented faster
- [x] Orchestrate frontend and backend versions
  - latest version of frontend should always point to latest version of backend.
  - currently, there is a period of time during deployment when the 2 versions don't match, and this causes errors for users.
- [ ] Create IAM users for dev branch and prod deployments

**App Features (Important)**
- [ ] Double check our sentry logging strategy #154 
- [ ] Get rid of SuperAdminWorld/ALL community edge case bugs #357 
- [x] Fix password reset process #386 
  - Content Team: Welcome text. Click this link to initiate. Make language clearer.
  - Don't make people enter their email twice. Ideally.
  - Make a better first impression.

**App Features (Nice to have)**
- [ ] Update unsafe react lifestyle component methods #408 
- [ ] Apply lat/lng input or location tracking to incident report form
- [ ] Row level security in postgres
- [x] Make our timestamps consistent #413 
- [ ] Get a devops email account instead of using personal email addresses
- [x] Reconsider our db migrations library
